### PR TITLE
Julia 0.7+ compatibility

### PR DESCRIPTION
**Pull request by raphapr**
In reply to https://github.com/Keno/Docker.jl/issues/10

Tested against Julia 1.0.1 on Linux.

### CODE REVIEW

**Comment by raphapr** [comment]
FYI @proflage @NaelsonDouglas

**Comment by proflage** [comment]
Many thanks, @raphapr!

I failed to load it in Julia 1.0.1 as a package. Maybe is something related to package registry, please see the log attached. 

How did you tested it?

```julia

alage@Andres-MacBook-Pro-2:~$ mv .julia .julia-1.0-Docker-buggy
alage@Andres-MacBook-Pro-2:~$ ll /opt/
total 0
drwxr-xr-x@  9 root  wheel   288B Nov 17  2016 X11
lrwxr-xr-x   1 root  wheel    52B Aug  8 11:59 julia -> /Applications/Julia-0.6.app/Contents/Resources/julia
lrwxr-xr-x   1 root  wheel    53B Aug 10 11:35 julia1.0 -> /Applications/Julia-1.0.app/Contents/Resources/julia/
drwxr-xr-x  13 root  wheel   416B Aug  4 10:31 local
alage@Andres-MacBook-Pro-2:~$ /opt/julia1.0/bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.1 (2018-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> add Docker
   Cloning default registries into /Users/alage/.julia/registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Docker [15bad361]:
 Docker [15bad361] log:
 ├─possible versions are: 0.0.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

(v1.0) pkg> 

julia> using Pkg
julia> Pkg.add("Docker")
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Docker [15bad361]:
 Docker [15bad361] log:
 ├─possible versions are: 0.0.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
Stacktrace:
 [1] #propagate_constraints!#61(::Bool, ::Function, ::Pkg.GraphType.Graph, ::Set{Int64}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1005
 [2] propagate_constraints! at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:946 [inlined]
 [3] #simplify_graph!#121(::Bool, ::Function, ::Pkg.GraphType.Graph, ::Set{Int64}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1460
 [4] simplify_graph! at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1460 [inlined]
 [5] macro expansion at ./logging.jl:319 [inlined]
 [6] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:338
 [7] #add_or_develop#58(::Array{Base.UUID,1}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1164
 [8] #add_or_develop at ./none:0 [inlined]
 [9] #add_or_develop#13(::Symbol, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:64
 [10] #add_or_develop#12 at ./none:0 [inlined]
 [11] #add_or_develop at ./none:0 [inlined]
 [12] #add_or_develop#11 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:28 [inlined]
 [13] #add_or_develop at ./none:0 [inlined]
 [14] #add_or_develop#10 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:27 [inlined]
 [15] #add_or_develop at ./none:0 [inlined]
 [16] #add#18 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69 [inlined]
 [17] add(::String) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69
 [18] top-level scope at none:0

julia> 

```

**Comment by raphapr** [comment]
@proflage Pkg.add pulls it from METADATA.jl (https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/Docker) which is out of date. Meanwhile, please use `Pkg.clone("Pkg.clone("https://github.com/Keno/Docker.jl.git")`

**Comment by proflage** [comment]
Thanks, @raphapr.

Anyways, I couldn't create a container because the connection was refused. The 4243 port is closed, do you think that this is an error from my local OSX Docker Engine installation (version 18.06.1-ce)? 

```julia

julia> Docker.create_container("127.0.0.1:4243","dmlt",memory=512*(10^6),portBindings=[22,22])
ERROR: IOError(Base.IOError("connect: connection refused (ECONNREFUSED)", -61) during request(http://127.0.0.1:4243/v1.21/containers/create))

Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
 [2] wait() at ./event.jl:255
 [3] wait(::Condition) at ./event.jl:46
 [4] stream_wait(::Sockets.TCPSocket, ::Condition) at ./stream.jl:47
 [5] wait_connected(::Sockets.TCPSocket) at ./stream.jl:263
 [6] connect at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:444 [inlined]
 [7] connect(::Sockets.IPv4, ::UInt64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:428
 [8] #getconnection#14(::Bool, ::Int64, ::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:require_ssl_verification, :iofunction),Tuple{Bool,Nothing}}}, ::Function, ::Type{Sockets.TCPSocket}, ::SubString{String}, ::SubString{String}) at /Users/alage/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:573
 [9] #getconnection at ./none:0 [inlined]
 [10] #getconnection#11(::Int64, ::Int64, ::Int64, ::Int64, ::Bool, ::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::Function, ::Type{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::SubString{String}, ::SubString{String}) at /Users/alage/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:522
 [11] (::getfield(HTTP.ConnectionPool, Symbol("#kw##getconnection")))(::NamedTuple{(:reuse_limit, :iofunction),Tuple{Int64,Nothing}}, ::typeof(HTTP.ConnectionPool.getconnection), ::Type{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::SubString{String}, ::SubString{String}) at ./none:0
 [12] #request#1(::Nothing, ::Type, ::Int64, ::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::Function, ::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at /Users/alage/.julia/packages/HTTP/YjRCz/src/ConnectionRequest.jl:41
 [13] #request at ./none:0 [inlined]
 [14] #request#1 at /Users/alage/.julia/packages/HTTP/YjRCz/src/ExceptionRequest.jl:19 [inlined]
 [15] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{Nothing}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at ./none:0
 [16] (::getfield(Base, Symbol("###44#45#46")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::Function, ::Type, ::Vararg{Any,N} where N) at ./error.jl:216
 [17] ##44#47 at ./none:0 [inlined]
 [18] #request#1 at /Users/alage/.julia/packages/HTTP/YjRCz/src/RetryRequest.jl:44 [inlined]
 [19] #request at ./none:0 [inlined]
 [20] #request#1(::VersionNumber, ::String, ::Nothing, ::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/alage/.julia/packages/HTTP/YjRCz/src/MessageRequest.jl:47
 [21] request at /Users/alage/.julia/packages/HTTP/YjRCz/src/MessageRequest.jl:28 [inlined]
 [22] #request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/alage/.julia/packages/HTTP/YjRCz/src/RedirectRequest.jl:24
 [23] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/alage/.julia/packages/HTTP/YjRCz/src/RedirectRequest.jl:21
 [24] #request#3(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/alage/.julia/packages/HTTP/YjRCz/src/HTTP.jl:302
 [25] request at /Users/alage/.julia/packages/HTTP/YjRCz/src/HTTP.jl:302 [inlined]
 [26] #request#4 at /Users/alage/.julia/packages/HTTP/YjRCz/src/HTTP.jl:316 [inlined]
 [27] #request at ./none:0 [inlined]
 [28] #create_container#1(::Cmd, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::String, ::Array{Int64,1}, ::Array{Any,1}, ::String, ::typeof(Docker.create_container), ::String, ::String) at /Users/alage/.julia/dev/Docker/src/Docker.jl:69
 [29] (::getfield(Docker, Symbol("#kw##create_container")))(::NamedTuple{(:memory, :portBindings),Tuple{Int64,Array{Int64,1}}}, ::typeof(Docker.create_container), ::String, ::String) at ./none:0
 [30] top-level scope at none:0

shell> nmap -p 4243 127.0.0.1
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-21 12:26 -03
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00026s latency).

PORT     STATE  SERVICE
4243/tcp closed vrml-multi-use

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

shell> nmap -F 127.0.0.1
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-21 12:26 -03
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00050s latency).
Not shown: 99 closed ports
PORT    STATE SERVICE
631/tcp open  ipp

Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds
```

**Comment by raphapr** [comment]
@proflage for default, dockerd doesn't listen on any network port. Please, try to kill your current dockerd process and run again with the following command: `/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243`.

**Pull request merged**
